//here all the data of the teachers will appear

export const teachers = [
  {
    firstName: "Francois",
    lastName: "du Toit",
    persalNumber: "2504",
    email: "francois.du.toit@example.com",
    registerClassNumber: "A123",
    majorSubjects: ["Mathematics", "Physics"],
    dateOfBirth: "1985-03-15",
    address: "123 Main Street, Cityville",
  },
  {
    firstName: "John",
    lastName: "Fortuin",
    persalNumber: "5705",
    email: "john.fortuin@example.com",
    registerClassNumber: "B456",
    majorSubjects: ["English", "History"],
    dateOfBirth: "1990-09-22",
    address: "456 Elm Street, Townsville",
  },
  {
    firstName: "HD",
    lastName: "Potgieter",
    persalNumber: "8899",
    email: "hd.potgieter@example.com",
    registerClassNumber: "C789",
    majorSubjects: ["Chemistry", "Biology"],
    dateOfBirth: "1988-07-02",
    address: "789 Oak Avenue, Villagetown",
  },
  {
    firstName: "Jaco",
    lastName: "Cronje",
    persalNumber: "7799",
    email: "jaco.cronje@example.com",
    registerClassNumber: "D012",
    majorSubjects: ["Computer Science", "Mathematics"],
    dateOfBirth: "1992-11-10",
    address: "012 Pine Street, Hamletville",
  },
  {
    firstName: "Jeandre",
    lastName: "Rautenbach",
    persalNumber: "4613",
    email: "jeandre.rautenbach@example.com",
    registerClassNumber: "E345",
    majorSubjects: ["Physics", "Chemistry"],
    dateOfBirth: "1987-06-25",
    address: "345 Cedar Road, Countryside",
  },
  {
    firstName: "Niel",
    lastName: "de Beer",
    persalNumber: "1315",
    email: "niel.de.beer@example.com",
    registerClassNumber: "F678",
    majorSubjects: ["English", "History"],
    dateOfBirth: "1991-04-05",
    address: "678 Maple Lane, Suburbia",
  },
  {
    firstName: "Sarah",
    lastName: "Johnson",
    persalNumber: "9922",
    email: "sarah.johnson@example.com",
    registerClassNumber: "G901",
    majorSubjects: ["Biology", "Chemistry"],
    dateOfBirth: "1995-08-17",
    address: "901 Oak Street, Cityville",
  },
  {
    firstName: "Michael",
    lastName: "Anderson",
    persalNumber: "6738",
    email: "michael.anderson@example.com",
    registerClassNumber: "H234",
    majorSubjects: ["Mathematics", "Computer Science"],
    dateOfBirth: "1989-12-03",
    address: "234 Elm Avenue, Townsville",
  },
  {
    firstName: "Emma",
    lastName: "Smith",
    persalNumber: "3471",
    email: "emma.smith@example.com",
    registerClassNumber: "I567",
    majorSubjects: ["English", "Literature"],
    dateOfBirth: "1994-02-14",
    address: "567 Pine Road, Villagetown",
  },
  {
    firstName: "David",
    lastName: "Williams",
    persalNumber: "5419",
    email: "david.williams@example.com",
    registerClassNumber: "J890",
    majorSubjects: ["History", "Political Science"],
    dateOfBirth: "1993-07-29",
    address: "890 Cedar Street, Hamletville",
  },
  {
    firstName: "Sophia",
    lastName: "Taylor",
    persalNumber: "2753",
    email: "sophia.taylor@example.com",
    registerClassNumber: "K123",
    majorSubjects: ["Mathematics", "Physics"],
    dateOfBirth: "1996-01-18",
    address: "123 Maple Lane, Countryside",
  },
  {
    firstName: "Liam",
    lastName: "Davis",
    persalNumber: "7064",
    email: "liam.davis@example.com",
    registerClassNumber: "L456",
    majorSubjects: ["Chemistry", "Biology"],
    dateOfBirth: "1990-05-07",
    address: "456 Oak Road, Suburbia",
  },
  {
    firstName: "Olivia",
    lastName: "Brown",
    persalNumber: "9337",
    email: "olivia.brown@example.com",
    registerClassNumber: "M789",
    majorSubjects: ["Computer Science", "Mathematics"],
    dateOfBirth: "1995-09-30",
    address: "789 Elm Street, Cityville",
  },
  {
    firstName: "William",
    lastName: "Miller",
    persalNumber: "4281",
    email: "william.miller@example.com",
    registerClassNumber: "N012",
    majorSubjects: ["Physics", "Chemistry"],
    dateOfBirth: "1992-03-08",
    address: "012 Pine Avenue, Townsville",
  },
  {
    firstName: "Ava",
    lastName: "Wilson",
    persalNumber: "1639",
    email: "ava.wilson@example.com",
    registerClassNumber: "O345",
    majorSubjects: ["English", "History"],
    dateOfBirth: "1997-06-21",
    address: "345 Cedar Road, Villagetown",
  },
  {
    firstName: "James",
    lastName: "Moore",
    persalNumber: "8567",
    email: "james.moore@example.com",
    registerClassNumber: "P678",
    majorSubjects: ["Biology", "Chemistry"],
    dateOfBirth: "1993-10-11",
    address: "678 Maple Lane, Hamletville",
  },
  {
    firstName: "Isabella",
    lastName: "Lee",
    persalNumber: "5023",
    email: "isabella.lee@example.com",
    registerClassNumber: "Q901",
    majorSubjects: ["Mathematics", "Computer Science"],
    dateOfBirth: "1998-04-24",
    address: "901 Oak Street, Countryside",
  },
  {
    firstName: "Benjamin",
    lastName: "Harris",
    persalNumber: "7175",
    email: "benjamin.harris@example.com",
    registerClassNumber: "R234",
    majorSubjects: ["English", "Literature"],
    dateOfBirth: "1997-08-04",
    address: "234 Elm Avenue, Suburbia",
  },
  {
    firstName: "Mia",
    lastName: "Clark",
    persalNumber: "3466",
    email: "mia.clark@example.com",
    registerClassNumber: "S567",
    majorSubjects: ["History", "Political Science"],
    dateOfBirth: "1996-12-19",
    address: "567 Pine Road, Villagetown",
  },
  {
    firstName: "Jacob",
    lastName: "Lewis",
    persalNumber: "9442",
    email: "jacob.lewis@example.com",
    registerClassNumber: "T890",
    majorSubjects: ["Mathematics", "Physics"],
    dateOfBirth: "1999-02-08",
    address: "890 Cedar Street, Cityville",
  },
  {
    firstName: "Charlotte",
    lastName: "Walker",
    persalNumber: "6898",
    email: "charlotte.walker@example.com",
    registerClassNumber: "U123",
    majorSubjects: ["Chemistry", "Biology"],
    dateOfBirth: "1994-06-30",
    address: "123 Main Street, Townsville",
  },
];

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
